fix: outputs more

diff --git a/.github/workflows/10-gotinput.yaml b/.github/workflows/10-gotinput.yaml
--- a/.github/workflows/10-gotinput.yaml
+++ b/.github/workflows/10-gotinput.yaml
@@ -23,4 +23,8 @@ jobs:
           IN_SHA: ${{ inputs.image_sha }}
         run: |-
           echo :notice: image_sha is $IN_SHA
+          if [ -z $IN_SHA ]; then
+            echo ":error:" Blank image_sha
+            exit 1
+          fi
 
